/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class change_pwd extends javax.swing.JInternalFrame {

    /**
     * Creates new form change_pwd
     */
    public change_pwd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        username_box = new javax.swing.JTextField();
        oldpwd_box = new javax.swing.JTextField();
        newpwd_box = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        confirmpwd_box = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CHANGE USER PASSWORD");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        username_box.setBackground(new java.awt.Color(255, 204, 204));
        username_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_boxActionPerformed(evt);
            }
        });
        jPanel1.add(username_box);
        username_box.setBounds(236, 32, 118, 20);

        oldpwd_box.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.add(oldpwd_box);
        oldpwd_box.setBounds(236, 70, 118, 20);

        newpwd_box.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.add(newpwd_box);
        newpwd_box.setBounds(236, 108, 118, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("USERNAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 35, 60, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("OLD PASSWORD");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 73, 89, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("NEW PASSWORD");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 108, 91, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("CONFIRM PASSWORD");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 150, 118, 14);

        confirmpwd_box.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.add(confirmpwd_box);
        confirmpwd_box.setBounds(236, 147, 118, 20);

        jButton1.setText("CHANGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(240, 180, 73, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\5145328-plain-picture.png")); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 0, 320, 230);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(74, 41, 394, 235);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CHANGE USER  PASSWORD ");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 16, 214, 19);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(158, 16, 26, 19);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\5220071-plain-picture.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 550, 330);

        setBounds(0, 0, 569, 362);
    }// </editor-fold>//GEN-END:initComponents

    private void username_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_boxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Connection myconnection;
            String path = "jdbc:mysql://localhost/";
            String place = "category";
            String uname = "root";

            String pass = "";
            myconnection = DriverManager.getConnection(path + place, uname, pass);

//             try
//             {
//                    String a="select * from logindatabase where username=? and password=?";
//                    PreparedStatement mystatement=myconnection.prepareStatement(a);
//                    mystatement.setString(1,username_box.getText());
//                    mystatement.setString(2,oldpwd_box.getText());
//                  ResultSet myresult = mystatement.executeQuery();
//                  if(myresult.next())
//                     {     if(myresult.getString("user_type").equals("admin"))
//                     {
            try {
                String b = "update logindatabase set password=? where username = ?  ";
                PreparedStatement mystatement1 = myconnection.prepareStatement(b);

//                       if(newpwd_box.getText()==confirmpwd_box.getText())
//                           
//                       {
                mystatement1.setString(2, username_box.getText());
                mystatement1.setString(1, newpwd_box.getText());
//                ResultSet myresult1 = mystatement1.executeQuery();
//                       }
//                       else
//                       { JOptionPane.showMessageDialog(rootPane, "pwd doesn't match ");
//                       }  
                if (mystatement1.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Saved Successfully");
//                    project1 obj = new project1();
//                    obj.setVisible(true);
//                    obj.setExtendedState(MAXIMIZED_BOTH);

                } else if (myresult.getString("user_type").equals("employee")) {
//                    emp_frame obj = new emp_frame();
//                    obj.setVisible(true);
//                    obj.setExtendedState(MAXIMIZED_BOTH);
                }
                this.dispose();

//                  else
//                     {JOptionPane.showMessageDialog(rootPane, "Wrong Username/Password Entered");
//                     }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Empty field " + e.getMessage());
            } finally {
                myconnection.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
        }
 
 
             // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirmpwd_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newpwd_box;
    private javax.swing.JTextField oldpwd_box;
    private javax.swing.JTextField username_box;
    // End of variables declaration//GEN-END:variables
}
