/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class company_detail extends javax.swing.JInternalFrame {

    /**
     * Creates new form company_detail
     */
    public company_detail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cid_box = new javax.swing.JTextField();
        c_namebox = new javax.swing.JTextField();
        c_codebox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        add_box = new javax.swing.JTextArea();
        mail_box = new javax.swing.JTextField();
        tel_box = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("ADD COMPANY DETAILS");
        setAutoscrolls(true);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setText("      ADD COMPANY DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(454, 81, 340, 48);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("COMPANY ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 170, 94, 16);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(585, 246, 0, 0);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 51));
        jLabel9.setText("COMPANY NAME");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(440, 210, 94, 16);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("TELEPHONE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 290, 68, 16);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("E-MAIL");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 430, 39, 20);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("OFFICE ADDRESS");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(440, 330, 97, 16);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("COMPANY CODE");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(440, 250, 93, 16);

        cid_box.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(cid_box);
        cid_box.setBounds(640, 170, 160, 30);

        c_namebox.setBackground(new java.awt.Color(255, 204, 204));
        c_namebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nameboxActionPerformed(evt);
            }
        });
        getContentPane().add(c_namebox);
        c_namebox.setBounds(640, 210, 160, 30);

        c_codebox.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(c_codebox);
        c_codebox.setBounds(640, 250, 160, 30);

        add_box.setBackground(new java.awt.Color(255, 204, 204));
        add_box.setColumns(20);
        add_box.setRows(5);
        jScrollPane1.setViewportView(add_box);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(640, 330, 143, 81);

        mail_box.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(mail_box);
        mail_box.setBounds(640, 430, 160, 30);

        tel_box.setBackground(new java.awt.Color(255, 204, 204));
        tel_box.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##########"))));
        getContentPane().add(tel_box);
        tel_box.setBounds(640, 290, 160, 30);

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 490, 57, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\Colorful-and-plain-theme-abstract-wallpapers.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, 0, 1480, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           try
           {
                 Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                  myconnection=DriverManager.getConnection(path+place, uname, pass);
 
             try
             {
                    String a="insert into company_table values(?,?,?,?,?,?)";
                    PreparedStatement mystatement=myconnection.prepareStatement(a);
                    mystatement.setString(1,cid_box .getText());
                    mystatement.setString(2,c_namebox .getText());
                    mystatement.setString(3,c_codebox .getText());
                    mystatement.setString(4, tel_box.getText());
                    mystatement.setString(5, add_box.getText());
                    mystatement.setString(6,mail_box .getText());
                  
                   
                  
                    
                  
 if(mystatement.executeUpdate()>0)
 {
   JOptionPane.showMessageDialog(rootPane, "Saved Successfully");
   cid_box .setText("");
   c_namebox .setText("");
   c_codebox .setText("");
   tel_box .setText("");
   add_box .setText("");
   mail_box .setText("");
           
                                           
 }
 
 }
 catch(Exception e)
 {
   JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 
 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c_nameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nameboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea add_box;
    private javax.swing.JTextField c_codebox;
    private javax.swing.JTextField c_namebox;
    private javax.swing.JTextField cid_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mail_box;
    private javax.swing.JFormattedTextField tel_box;
    // End of variables declaration//GEN-END:variables
}
