/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class company_list extends javax.swing.JInternalFrame {

    /**
     * Creates new form company_list
     */
    public company_list() {
        initComponents();
//         try
//           {
//                 Connection myconnection;
//                 String path="jdbc:mysql://localhost/";
//                 String place="category";
//                 String uname="root" ;
//                
//                 String pass="";
//                  myconnection=DriverManager.getConnection(path+place, uname, pass);
//         try
//                      {    
//                            
//                            
//                            String a="select * from company_table";
//                            PreparedStatement mystatement = myconnection.prepareStatement(a);
//                            ResultSet myresult=mystatement.executeQuery();
//                   
//                             if(myresult.next())
//                             {{
//                                          DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();
//           
//                                        do
//                                        {  String COMPANY_ID,COMPANY_NAME,COMPANY_CODE,TELEPHONE,ADDRESS,EMAIL;
//                                           COMPANY_ID=myresult.getString("company_id");
//                                           COMPANY_NAME=myresult.getString("company_name");
//                                           COMPANY_CODE=myresult.getString("company_code");
//                                           TELEPHONE=myresult.getString("telphone");
//                                           ADDRESS=myresult.getString("address");
//                                           EMAIL=myresult.getString("email");
//                                          
//                                           mymodel.addRow(new Object[]{COMPANY_ID,COMPANY_NAME,COMPANY_CODE,TELEPHONE,ADDRESS,EMAIL});
//                                          }
//                                 while(myresult.next());}}
//                      
//        
//                  else
//                {JOptionPane.showMessageDialog(rootPane, "No company exist");
//                }
//             }
//             catch(Exception e)
//            {
//               JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
//            }
//               
//
//                 
//                  
//          finally
//            {
//            myconnection.close();
//            }
// 
// 
//            }
//          catch(Exception e)
//     {
//      JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
//     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        search_box = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("COMPANY LIST");
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COMPANY_ID", "COMPANY_NAME", "COMPANY_CODE", "TELEPHONE", "ADDRESS", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 50, 1080, 510);

        search_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_boxActionPerformed(evt);
            }
        });
        getContentPane().add(search_box);
        search_box.setBounds(100, 20, 130, 20);

        jButton1.setText("SEARCH COMPANY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 20, 140, 23);

        jButton2.setText("PRINT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1030, 20, 80, 23);

        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(564, 0, 0, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\5220071-plain-picture.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 1470, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_boxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try
           {
                 Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                  myconnection=DriverManager.getConnection(path+place, uname, pass);
         try
                      {    
                            
                            
                            String a="select * from company_table where company_id=? or company_name=? ";
                            PreparedStatement mystatement = myconnection.prepareStatement(a);
                            mystatement.setString(1, search_box.getText());
                            mystatement.setString(2, search_box.getText());
                           
                            
                            
                            ResultSet myresult=mystatement.executeQuery();
                   
                             if(myresult.next())
                             {{
                                          DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();
           
                                        do
                                        {  String COMPANY_ID,COMPANY_NAME,COMPANY_CODE,TELEPHONE,ADDRESS,EMAIL;
                                           COMPANY_ID=myresult.getString("company_id");
                                           COMPANY_NAME=myresult.getString("company_name");
                                           COMPANY_CODE=myresult.getString("company_code");
                                           TELEPHONE=myresult.getString("telphone");
                                           ADDRESS=myresult.getString("address");
                                           EMAIL=myresult.getString("email");
                                          
                                           mymodel.addRow(new Object[]{COMPANY_ID,COMPANY_NAME,COMPANY_CODE,TELEPHONE,ADDRESS,EMAIL});
                                          }
                                 while(myresult.next());}}
                      
        
                  else
                {JOptionPane.showMessageDialog(rootPane, "No company exist");
                }
             }
             catch(Exception e)
            {
               JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
            }
               

                 
                  
          finally
            {
            myconnection.close();
            }
 
 
            }
          catch(Exception e)
     {
      JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
     }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  MessageFormat myheader=new MessageFormat("List of Company") ;
       MessageFormat myfooter=new MessageFormat("page{0}") ;
       try
        {jTable1.print(JTable.PrintMode.FIT_WIDTH,myheader,myfooter);
        }
       catch(PrinterException e )
       { JOptionPane.showMessageDialog(rootPane, "Error while printing due to" + e.getMessage());
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.TextField search_box;
    // End of variables declaration//GEN-END:variables
}
