/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;
import java.awt.Image;
import java.io.File;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PC
 */
public class edit_employee extends javax.swing.JInternalFrame {
File myfile;
String oldfilename;
    /**
     * Creates new form project2
     */
    public edit_employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        employeename_box = new java.awt.TextField();
        employdes_box = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        employeeid_box = new javax.swing.JFormattedTextField();
        label6 = new java.awt.Label();
        jButton2 = new javax.swing.JButton();
        male2 = new javax.swing.JRadioButton();
        female2 = new javax.swing.JRadioButton();
        emp_addr = new java.awt.TextArea();
        dob2 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label7 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder());
        setClosable(true);
        setForeground(java.awt.Color.gray);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("EDIT EMPLOYEE DETAILS");
        getContentPane().setLayout(null);

        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("EMPLOYEE ID");
        getContentPane().add(label1);
        label1.setBounds(160, 180, 146, 20);

        label2.setBackground(new java.awt.Color(255, 255, 255));
        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("EMPLOYEE NAME");
        getContentPane().add(label2);
        label2.setBounds(160, 220, 146, 20);

        label3.setBackground(new java.awt.Color(255, 255, 255));
        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("DOB");
        getContentPane().add(label3);
        label3.setBounds(160, 440, 50, 20);

        employeename_box.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        employeename_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeename_boxActionPerformed(evt);
            }
        });
        getContentPane().add(employeename_box);
        employeename_box.setBounds(360, 220, 221, 30);
        getContentPane().add(employdes_box);
        employdes_box.setBounds(360, 260, 221, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 500, 100, 23);

        employeeid_box.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        employeeid_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeid_boxActionPerformed(evt);
            }
        });
        getContentPane().add(employeeid_box);
        employeeid_box.setBounds(360, 180, 221, 30);

        label6.setBackground(new java.awt.Color(255, 204, 204));
        label6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 0, 51));
        label6.setName(""); // NOI18N
        label6.setText("         EDIT EMPLOYEE DETAILS");
        getContentPane().add(label6);
        label6.setBounds(210, 60, 386, 53);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.png"))); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 60, 55, 53);

        buttonGroup2.add(male2);
        male2.setText("MALE");
        male2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male2ActionPerformed(evt);
            }
        });
        getContentPane().add(male2);
        male2.setBounds(360, 300, 70, 23);

        buttonGroup2.add(female2);
        female2.setText("FEMALE");
        female2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female2ActionPerformed(evt);
            }
        });
        getContentPane().add(female2);
        female2.setBounds(450, 300, 80, 23);
        getContentPane().add(emp_addr);
        emp_addr.setBounds(360, 340, 170, 80);
        getContentPane().add(dob2);
        dob2.setBounds(360, 440, 222, 30);

        jLabel4.setBackground(new java.awt.Color(51, 255, 204));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 201, 0, 0);

        jButton3.setText("SEARCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(610, 180, 73, 23);

        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(610, 220, 73, 23);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("DELETE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(480, 500, 90, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "emp_id", "emp_name", "emp_desg", "gender", "address", "dob"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(730, 180, 570, 290);

        label4.setBackground(new java.awt.Color(255, 255, 255));
        label4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("EMPLOYEE DESIGNATION");
        getContentPane().add(label4);
        label4.setBounds(160, 260, 146, 20);

        label5.setBackground(new java.awt.Color(255, 255, 255));
        label5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("GENDER");
        getContentPane().add(label5);
        label5.setBounds(160, 300, 50, 20);

        label7.setBackground(new java.awt.Color(255, 255, 255));
        label7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label7.setText("ADDRESS");
        getContentPane().add(label7);
        label7.setBounds(160, 340, 146, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\5220071-plain-picture.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, -70, 1350, 1330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeename_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeename_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeename_boxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             try
           {
                 Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                  myconnection=DriverManager.getConnection(path+place, uname, pass);
 
             try
             {
                    String a="update emp_table set emp_name=?,"+"emp_desig=?,gender=?, address=?,dob=?"+"where emp_id=?";
                    PreparedStatement mystatement=myconnection.prepareStatement(a);
               
                    mystatement.setString(6,employeeid_box .getText());
                    mystatement.setString(1, employeename_box.getText());
                    mystatement.setString(2, employdes_box.getText());
                    if(male2.isSelected())
                       {mystatement.setString(3,"MALE");
                       }
                    else if(female2.isSelected())
                       {mystatement.setString(3,"FEMALE");
                       }
                    mystatement.setString(4,emp_addr.getText());
                  SimpleDateFormat myformat=new SimpleDateFormat("yyyy-MM-dd");
                    mystatement.setString(5,myformat.format(dob2.getDate()));  
                  
                    
                  
 if(mystatement.executeUpdate()>0)
 {
   JOptionPane.showMessageDialog(rootPane, "Saved Successfully");
  employeeid_box.setText("");
   employeename_box.setText("");
   employdes_box.setText("");
   buttonGroup2.clearSelection();
   emp_addr.setText("");
   dob2.setDate(null);
   
           
                                           
 }
 
 }
 catch(Exception e)
 {
   JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 
 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void employeeid_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeid_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeid_boxActionPerformed

    private void female2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female2ActionPerformed

    private void male2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_male2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try
 {    Connection myconnection;
        
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                 myconnection=DriverManager.getConnection(path+place, uname, pass);
 
 
                      try
                        {
                          String myquery="select * from emp_table where emp_id like ?";
                          PreparedStatement mystatement = myconnection.prepareStatement(myquery);
                          mystatement.setString(1, "%" + employeeid_box.getText() + "%");
                          ResultSet myresult=mystatement.executeQuery();
 
                         if(myresult.next())
                            {
                              DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
                              
                              mymodel.setRowCount(0);
                              do
                              { 
                                           String emp_id,emp_name,emp_desg,gender,address,dob;
                                           emp_id=myresult.getString("emp_id");
                                           emp_name=myresult.getString("emp_name");
                                           emp_desg=myresult.getString("emp_desig");
                                           gender=myresult.getString("gender");
                                           address=myresult.getString("address");
                                           dob=myresult.getString("dob");
                                          
                                           mymodel.addRow(new Object[]{emp_id,emp_name,emp_desg,gender,address,dob});
                               }
                               while(myresult.next());
 
                               }
                        else
                        {
                          JOptionPane.showMessageDialog(rootPane,"No Info available");
                         }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Query due to " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection due to " + e.getMessage());
 }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try
 {    Connection myconnection;
        
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                 myconnection=DriverManager.getConnection(path+place, uname, pass);
 
 
                      try
                        {
                          String myquery="select * from emp_table where emp_name like ?";
                          PreparedStatement mystatement = myconnection.prepareStatement(myquery);
                          mystatement.setString(1, "%" + employeename_box.getText() + "%");
                          ResultSet myresult=mystatement.executeQuery();
 
                         if(myresult.next())
                            {
                              DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
                          
                              mymodel.setRowCount(0);
                              do
                              { 
                                           
                                           String emp_id,emp_name,emp_desg,gender,address,dob;
                                           emp_id=myresult.getString("emp_id");
                                           emp_name=myresult.getString("emp_name");
                                           emp_desg=myresult.getString("emp_desig");
                                           gender=myresult.getString("gender");
                                           address=myresult.getString("address");
                                           dob=myresult.getString("dob");
                                          
                                           mymodel.addRow(new Object[]{emp_id,emp_name,emp_desg,gender,address,dob});
                                           
                                          
                           
                               }
                               while(myresult.next());
 
                               }
                        else
                        {
                          JOptionPane.showMessageDialog(rootPane,"No Info available");
                         }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Query due to " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection due to " + e.getMessage());
 }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
               int result=JOptionPane.showConfirmDialog(rootPane, "Do you really want to delete?", 
                  "Are you sure?", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
 
           if(result==JOptionPane.YES_OPTION)
  {
          try
       {
                 Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                 myconnection=DriverManager.getConnection(path+place, uname, pass);
 
               try
                {
                   String a="delete from emp_table where emp_id=?";
                   PreparedStatement mystatement=myconnection.prepareStatement(a); 
                   mystatement.setString(1, employeeid_box.getText());
 
                  if(mystatement.executeUpdate()>0)
                     
 {
 JOptionPane.showMessageDialog(rootPane, "Deleted Successfully");
    employeeid_box.setText("");
   employeename_box.setText("");
   employdes_box.setText("");
   buttonGroup2.clearSelection();
   emp_addr.setText("");
   dob2.setDate(null);
   
 }
 else
 {
 JOptionPane.showMessageDialog(rootPane, "Cannot delete");
 }
 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 
 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }
 }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
int row = jTable1.getSelectedRow();
 int column = 0;
 String emp_id=jTable1.getValueAt(row, column).toString();
 try
 { Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                 myconnection=DriverManager.getConnection(path+place, uname, pass);
 
 try
 {
 String myquery="select * from emp_table where emp_id=?";
 PreparedStatement mystatement = myconnection.prepareStatement(myquery);
 mystatement.setString(1, emp_id);
 ResultSet myresult=mystatement.executeQuery();
 
 if(myresult.next())
 {employeeid_box.setText(emp_id);

                                                  employeename_box.setText(myresult.getString("emp_name"));
                                           employdes_box.setText(myresult.getString("emp_desig"));
                                          if(myresult.getString("gender").equals("MALE"))
                                            {male2.setSelected(true);
                                             }
                                             else if(myresult.getString("gender").equals("FEMALE"))
                                             {female2.setSelected(true);
                                              }
                                          
                                           emp_addr.setText(myresult.getString("address"));
                                          dob2.setDate(myresult.getDate("dob"));
                                        
 }
 else
 {
 JOptionPane.showMessageDialog(rootPane,"no employee ID exist ");
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Query due to " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection due to " + e.getMessage());
 }         // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser dob2;
    private java.awt.TextArea emp_addr;
    private java.awt.TextField employdes_box;
    private javax.swing.JFormattedTextField employeeid_box;
    private java.awt.TextField employeename_box;
    private javax.swing.JRadioButton female2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private javax.swing.JRadioButton male2;
    // End of variables declaration//GEN-END:variables
}
