/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class emp_login extends javax.swing.JInternalFrame {

    /**
     * Creates new form emp_login
     */
    public emp_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password_box = new javax.swing.JPasswordField();
        empusername_box = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("employee login creation");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setText("Employee Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 100, 116, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 150, 70, 30);

        password_box.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(password_box);
        password_box.setBounds(220, 150, 111, 30);

        empusername_box.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(empusername_box);
        empusername_box.setBounds(220, 100, 111, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("create ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 200, 80, 23);

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("CREATE EMPLOYEE LOGIN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 50, 160, 15);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 50, 20, 22);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\5220071-plain-picture.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 410, 280);

        setBounds(0, 0, 421, 312);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
           {
                 Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                  myconnection=DriverManager.getConnection(path+place, uname, pass);
 
             try
             {
                    String a="insert into logindatabase values(?,?,?)";
                    PreparedStatement mystatement=myconnection.prepareStatement(a);
                    mystatement.setString(1,empusername_box.getText());
                    mystatement.setString(2,password_box.getText());
                    mystatement.setString(3,"employee");
                              
                    
                  
                                 if(mystatement.executeUpdate()>0)
                        {
                                  JOptionPane.showMessageDialog(rootPane, "employee created Successfully");
                                   empusername_box.setText("");
                                   password_box.setText("");
                                    JOptionPane.showMessageDialog(rootPane, "employee created Successfully");
    
  
           
                                           
                        }
 
             }
            catch(Exception e)
             {
                JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
             }
           finally
             {
             myconnection.close();
             }
 
 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }        
                                   
         
              // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField empusername_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField password_box;
    // End of variables declaration//GEN-END:variables
}
