/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.*;
import java.awt.print.*;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class productlist1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form productlist1
     */
    public productlist1() {
        initComponents();
        try
           {
                 Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                  myconnection=DriverManager.getConnection(path+place, uname, pass);
                  try{ String b="select * from categorytable";
                            PreparedStatement mystatement1 = myconnection.prepareStatement(b);
                            ResultSet myresult1= mystatement1.executeQuery();
                            if(myresult1.next())
                                   {   do
                                       {
                                           catbox.addItem(myresult1.getString("catname"));
                                           
                                       }
                                        while(myresult1.next());
                                    }
                            else
                            {JOptionPane.showMessageDialog(rootPane, "No category exist");
                            }
                  }
                    catch(Exception e)
            {
               JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
            }
           
 
//                  try
//                      {    
//                            
//                            
//                            String a="select * from producttable";
//                            PreparedStatement mystatement = myconnection.prepareStatement(a);
//                            ResultSet myresult=mystatement.executeQuery();
//                   
//                             if(myresult.next())
//                             {{
//                                          DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();
//                                          String CUSTOMERDETAIL,ENGINECHASISNO,INSUREDVALUE,PERIOD,CONTACT,FROMDATE,UPTO,VEHICLEDETAIL;
//                                        do
//                                        {   CUSTOMERDETAIL=myresult.getString("customer_id_nam");
//                                            ENGINECHASISNO=myresult.getString("engine_chasis");
//                                           INSUREDVALUE=myresult.getString("insuredvalue");
//                                           PERIOD=myresult.getString("periods");
//                                           CONTACT=myresult.getString("contact_no");
//                                           FROMDATE=myresult.getString("date1");
//                                           UPTO=myresult.getString("date2");
//                                          
//                                           VEHICLEDETAIL=myresult.getString("vehicle_no_name");
//                                mymodel.addRow(new Object[]{CUSTOMERDETAIL,ENGINECHASISNO,INSUREDVALUE,PERIOD,CONTACT,FROMDATE,UPTO,VEHICLEDETAIL});
//                                          }
//                                 while(myresult.next());}}
//                      
//        
//                  else
//                {JOptionPane.showMessageDialog(rootPane, "No customer exist");
//                }
//             }
//             catch(Exception e)
//            {
//               JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
//            }
//               
//
//                 
//                  
          finally
            {
            myconnection.close();
            }
 
 
            }
          catch(Exception e)
     {
      JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        catbox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        subcat_box = new javax.swing.JComboBox<>();
        s_box = new javax.swing.JTextField();
        search_box = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 0));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CUSTOMERS LIST");
        getContentPane().setLayout(null);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setForeground(new java.awt.Color(0, 102, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUSTOMERDETAIL", "ENGINECHASISNO", "INSUREDVALUE", "PERIOD", "CONTACT", "FROMDATE", "UPTO", "VEHICLEDETAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 110, 990, 430);

        catbox.setForeground(new java.awt.Color(51, 51, 255));
        catbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE TYPE" }));
        catbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catboxActionPerformed(evt);
            }
        });
        getContentPane().add(catbox);
        catbox.setBounds(730, 50, 170, 31);

        jButton1.setForeground(new java.awt.Color(51, 0, 204));
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(630, 550, 120, 30);

        subcat_box.setForeground(new java.awt.Color(0, 0, 255));
        subcat_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE SUBTYPE" }));
        subcat_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subcat_boxActionPerformed(evt);
            }
        });
        getContentPane().add(subcat_box);
        subcat_box.setBounds(940, 50, 150, 31);
        getContentPane().add(s_box);
        s_box.setBounds(230, 50, 120, 30);

        search_box.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobile-search.png"))); // NOI18N
        search_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_boxActionPerformed(evt);
            }
        });
        getContentPane().add(search_box);
        search_box.setBounds(380, 50, 55, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\5220071-plain-picture.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -20, 1500, 1240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catboxActionPerformed
//try
//           {
//                 Connection myconnection;
//                 String path="jdbc:mysql://localhost/";
//                 String place="category";
//                 String uname="root" ;
//                
//                 String pass="";
//                  myconnection=DriverManager.getConnection(path+place, uname, pass);
// 
//                  try
//                      {
//                            String a="select * from producttable where catname=? ";
//                            PreparedStatement mystatement = myconnection.prepareStatement(a);
//                             mystatement.setString(1,catbox.getSelectedItem().toString());
//                          
//                             ResultSet myresult = mystatement.executeQuery();
//                                  
//                             if(myresult.next())
//                             {{
//                                          DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();
//           
//                                          String CUSTOMERDETAIL,ENGINECHASISNO,INSUREDVALUE,PERIOD,CONTACT,FROMDATE,UPTO,VEHICLEDETAIL;
//                                         
//                                          mymodel.setRowCount(0);
//                                          do
//                                          {CUSTOMERDETAIL=myresult.getString("customer_id_nam");
//                                            ENGINECHASISNO=myresult.getString("engine_chasis");
//                                           INSUREDVALUE=myresult.getString("insuredvalue");
//                                           PERIOD=myresult.getString("periods");
//                                           CONTACT=myresult.getString("contact_no");
//                                           FROMDATE=myresult.getString("date1");
//                                           UPTO=myresult.getString("date2");
//                                          
//                                           VEHICLEDETAIL=myresult.getString("vehicle_no_name");
//                                mymodel.addRow(new Object[]{CUSTOMERDETAIL,ENGINECHASISNO,INSUREDVALUE,PERIOD,CONTACT,FROMDATE,UPTO,VEHICLEDETAIL});
//                                         
//                                           
//                                          }
//                                          while(myresult.next());}
//                                          
//                               }
//                     
//                     
//        
//                  else
//                {JOptionPane.showMessageDialog(rootPane, "No customer exist");
//                }
//             }
//             catch(Exception e)
//            {
//               JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
//            }
//          finally
//            {
//            myconnection.close();
//            }
// 
// 
//            }
//          catch(Exception e)
//     {
//      JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
//     }
 try
           {
                 Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                  myconnection=DriverManager.getConnection(path+place, uname, pass);
                  try{ String b="select * from producttable where catname=?";
                            PreparedStatement mystatement1 = myconnection.prepareStatement(b);
                            mystatement1.setString(1, catbox.getSelectedItem().toString());
                            ResultSet myresult1= mystatement1.executeQuery();
                            if(myresult1.next())
                                   {   do
                                       {
                                           subcat_box.addItem(myresult1.getString("subcatname"));
                                           
                                       }
                                        while(myresult1.next());
                                    }
                            else
                            {JOptionPane.showMessageDialog(rootPane, "No category exist");
                            }
                  }
                    catch(Exception e)
            {
               JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
            }
                  finally
            {
            myconnection.close();
            }
 
 
            }
          catch(Exception e)
     {
      JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
     }
           
    }//GEN-LAST:event_catboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       MessageFormat myheader=new MessageFormat("List of customers") ;
       MessageFormat myfooter=new MessageFormat("page{0}") ;
       try
        {jTable1.print(JTable.PrintMode.FIT_WIDTH,myheader,myfooter);
        }
       catch(PrinterException e )
       { JOptionPane.showMessageDialog(rootPane, "Error while printing due to" + e.getMessage());
       }





// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void subcat_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subcat_boxActionPerformed
try
           {
                 Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                  myconnection=DriverManager.getConnection(path+place, uname, pass);
 
                  try
                      {
                            String a="select * from producttable where subcatname=? ";
                            PreparedStatement mystatement = myconnection.prepareStatement(a);
                             mystatement.setString(1,subcat_box.getSelectedItem().toString());
                          
                             ResultSet myresult = mystatement.executeQuery();
                                  
                             if(myresult.next())
                             {{
                                          DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();
           
                                          String CUSTOMERDETAIL,ENGINECHASISNO,INSUREDVALUE,PERIOD,CONTACT,FROMDATE,UPTO,VEHICLEDETAIL;
                                         
                                          mymodel.setRowCount(0);
                                          do
                                          {CUSTOMERDETAIL=myresult.getString("customer_id_nam");
                                            ENGINECHASISNO=myresult.getString("engine_chasis");
                                           INSUREDVALUE=myresult.getString("insuredvalue");
                                           PERIOD=myresult.getString("periods");
                                           CONTACT=myresult.getString("contact_no");
                                           FROMDATE=myresult.getString("date1");
                                           UPTO=myresult.getString("date2");
                                          
                                           VEHICLEDETAIL=myresult.getString("vehicle_no_name");
                                mymodel.addRow(new Object[]{CUSTOMERDETAIL,ENGINECHASISNO,INSUREDVALUE,PERIOD,CONTACT,FROMDATE,UPTO,VEHICLEDETAIL});
                                         
                                           
                                          }
                                          while(myresult.next());}
                                          
                               }
                     
                     
        
                  else
                {JOptionPane.showMessageDialog(rootPane, "No customer exist");
                }
             }
             catch(Exception e)
            {
               JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
            }
          finally
            {
            myconnection.close();
            }
 
 
            }
          catch(Exception e)
     {
      JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
     }        // TODO add your handling code here:
    }//GEN-LAST:event_subcat_boxActionPerformed

    private void search_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_boxActionPerformed
            try
           {
                 Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                  myconnection=DriverManager.getConnection(path+place, uname, pass);
       try
                      {    
                            
                            
                            String a="select * from producttable where customer_id_nam=?";
                            PreparedStatement mystatement = myconnection.prepareStatement(a);
                              mystatement.setString(1, s_box.getText());
                            ResultSet myresult=mystatement.executeQuery();
                   
                             if(myresult.next())
                             {{
                                          DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();
                                          String CUSTOMERDETAIL,ENGINECHASISNO,INSUREDVALUE,PERIOD,CONTACT,FROMDATE,UPTO,VEHICLEDETAIL;
                                        do
                                        {   CUSTOMERDETAIL=myresult.getString("customer_id_nam");
                                            ENGINECHASISNO=myresult.getString("engine_chasis");
                                           INSUREDVALUE=myresult.getString("insuredvalue");
                                           PERIOD=myresult.getString("periods");
                                           CONTACT=myresult.getString("contact_no");
                                           FROMDATE=myresult.getString("date1");
                                           UPTO=myresult.getString("date2");
                                          
                                           VEHICLEDETAIL=myresult.getString("vehicle_no_name");
                                mymodel.addRow(new Object[]{CUSTOMERDETAIL,ENGINECHASISNO,INSUREDVALUE,PERIOD,CONTACT,FROMDATE,UPTO,VEHICLEDETAIL});
                                          }
                                 while(myresult.next());}}
                      
        
                  else
                {JOptionPane.showMessageDialog(rootPane, "No customer exist");
                }
             }
             catch(Exception e)
            {
               JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
            }
        finally
            {
            myconnection.close();
            }
 
 
            }
          catch(Exception e)
     {
      JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
     }   
                       // TODO add your handling code here:
    }//GEN-LAST:event_search_boxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> catbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField s_box;
    private javax.swing.JButton search_box;
    private javax.swing.JComboBox<String> subcat_box;
    // End of variables declaration//GEN-END:variables
}
