/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author PC
 */
public class project6 extends javax.swing.JInternalFrame {

    /**
     * Creates new form project2
     */
    public project6() {
        initComponents();
         try
        {        
                  Connection myconnection;
        
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                 myconnection=DriverManager.getConnection(path+place, uname, pass);
                 try{
                                    String b="select * from categorytable";
                                    PreparedStatement mystatement=myconnection.prepareStatement(b);
                                    ResultSet myresult = mystatement.executeQuery();
                                    if(myresult.next())
                                        {do
                                            {    category_box.addItem(myresult.getString("catname"));
                                            }
                                        while(myresult.next());
                                        }
                                   else
                                    { JOptionPane.showMessageDialog(rootPane, "No categories exist");
                                    }
                                    
                                    
                                    
         
                   }
 
 
               catch(Exception e)
                  {
              JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
                  }
                finally
                {
                 myconnection.close();
                }
 
 
         }
     catch(Exception e)
            {
             JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        colorProfileManager1 = new org.apache.batik.css.engine.value.svg.ColorProfileManager();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        custome_id_namebox = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        periods_box = new javax.swing.JFormattedTextField();
        insured_box = new javax.swing.JFormattedTextField();
        engine_chasis_box = new javax.swing.JFormattedTextField();
        label6 = new java.awt.Label();
        jButton2 = new javax.swing.JButton();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        category_box = new javax.swing.JComboBox<>();
        subcategory_box = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date1box = new javax.swing.JFormattedTextField();
        date2box = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        customer_addbox = new java.awt.TextArea();
        vehicle_box = new javax.swing.JTextField();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        contact_box = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 153, 0)));
        setClosable(true);
        setForeground(new java.awt.Color(204, 255, 51));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ADD CUSTOMER'S INSURANCE");
        setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/editPencil.png"))); // NOI18N
        getContentPane().setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("ENGINE NO./CHASIS NO.");
        getContentPane().add(label1);
        label1.setBounds(290, 190, 218, 20);

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("VEHICLE NO./VEHICLE NAME/MFD.YEAR");
        getContentPane().add(label2);
        label2.setBounds(290, 150, 195, 20);

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("CONTACT NO.");
        getContentPane().add(label3);
        label3.setBounds(290, 230, 195, 20);

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("ADDRESS");
        getContentPane().add(label4);
        label4.setBounds(290, 380, 195, 20);

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("INSURED VALUE");
        getContentPane().add(label5);
        label5.setBounds(290, 520, 195, 20);

        custome_id_namebox.setBackground(new java.awt.Color(204, 255, 255));
        custome_id_namebox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        custome_id_namebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custome_id_nameboxActionPerformed(evt);
            }
        });
        getContentPane().add(custome_id_namebox);
        custome_id_namebox.setBounds(540, 90, 457, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 570, 109, 23);

        periods_box.setBackground(new java.awt.Color(204, 255, 255));
        periods_box.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        periods_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periods_boxActionPerformed(evt);
            }
        });
        getContentPane().add(periods_box);
        periods_box.setBounds(540, 270, 60, 30);

        insured_box.setBackground(new java.awt.Color(204, 255, 255));
        insured_box.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(insured_box);
        insured_box.setBounds(540, 520, 260, 30);

        engine_chasis_box.setBackground(new java.awt.Color(204, 255, 255));
        engine_chasis_box.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        engine_chasis_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engine_chasis_boxActionPerformed(evt);
            }
        });
        getContentPane().add(engine_chasis_box);
        engine_chasis_box.setBounds(540, 180, 456, 30);

        label6.setBackground(new java.awt.Color(0, 204, 204));
        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setForeground(new java.awt.Color(0, 0, 255));
        label6.setName(""); // NOI18N
        label6.setText("         ADD CUSTOMER'S INSURANCE");
        getContentPane().add(label6);
        label6.setBounds(473, 11, 335, 53);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.png"))); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(388, 11, 75, 53);

        label7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label7.setText("INSURANCE SUBTYPE");
        getContentPane().add(label7);
        label7.setBounds(290, 480, 126, 20);

        label8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label8.setText("INSURANCE TYPE");
        getContentPane().add(label8);
        label8.setBounds(290, 440, 117, 20);

        category_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE TYPE" }));
        category_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_boxActionPerformed(evt);
            }
        });
        getContentPane().add(category_box);
        category_box.setBounds(540, 440, 206, 20);

        subcategory_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE TYPE FIRST" }));
        subcategory_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subcategory_boxActionPerformed(evt);
            }
        });
        getContentPane().add(subcategory_box);
        subcategory_box.setBounds(540, 480, 206, 20);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(389, 303, 0, 0);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("TO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(670, 330, 16, 16);

        date1box.setBackground(new java.awt.Color(204, 255, 255));
        date1box.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yy"))));
        getContentPane().add(date1box);
        date1box.setBounds(540, 320, 120, 30);

        date2box.setBackground(new java.awt.Color(204, 255, 255));
        date2box.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yy"))));
        getContentPane().add(date2box);
        date2box.setBounds(700, 320, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("INR");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(810, 530, 30, 14);

        customer_addbox.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(customer_addbox);
        customer_addbox.setBounds(540, 369, 280, 50);

        vehicle_box.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(vehicle_box);
        vehicle_box.setBounds(540, 140, 457, 30);

        label9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label9.setText("CUSTOMER ID/CUSTOMER NAME");
        getContentPane().add(label9);
        label9.setBounds(290, 100, 195, 20);

        label10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label10.setText("PERIODS OF INSURANCE(in years)");
        getContentPane().add(label10);
        label10.setBounds(290, 270, 195, 20);

        label11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label11.setText("DATE OF INSURANCE");
        getContentPane().add(label11);
        label11.setBounds(290, 320, 195, 20);

        contact_box.setBackground(new java.awt.Color(204, 255, 255));
        contact_box.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##########"))));
        getContentPane().add(contact_box);
        contact_box.setBounds(540, 220, 250, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\Colorful-and-plain-theme-abstract-wallpapers.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -80, 1450, 1320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void periods_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periods_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periods_boxActionPerformed

    private void custome_id_nameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custome_id_nameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custome_id_nameboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             try
           {
                 Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                  myconnection=DriverManager.getConnection(path+place, uname, pass);
 
             try
             {
                    String a="insert into producttable values(?,?,?,?,?,?,?,?,?,?,?)";
                    PreparedStatement mystatement=myconnection.prepareStatement(a);
                    mystatement.setString(1, custome_id_namebox.getText());
                    mystatement.setString(2, engine_chasis_box.getText());
                    mystatement.setString(3, contact_box.getText());
                    mystatement.setString(4, periods_box.getText());
                    mystatement.setString(5, insured_box.getText());
                    mystatement.setString(6, category_box.getSelectedItem().toString());
                    mystatement.setString(7, subcategory_box.getSelectedItem().toString());
                    mystatement.setString(8, date1box.getText());
                    mystatement.setString(9, date2box.getText());
                    mystatement.setString(10, customer_addbox.getText());
                    mystatement.setString(11, vehicle_box.getText());
                    
 if(mystatement.executeUpdate()>0)
 {
   JOptionPane.showMessageDialog(rootPane, "Saved Successfully");
   engine_chasis_box.setText("");
   custome_id_namebox.setText("");
   contact_box.setText("");
   periods_box.setText("");
   insured_box.setText("");
   date1box.setText("");
   date2box.setText("");
   customer_addbox.setText("");
   vehicle_box.setText("");
  // category_box.setSelectedIndex(0);
  // subcategory_box.setSelectedIndex(0);
           
                                           
 }
 
 }
 catch(Exception e)
 {
   JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 
 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void engine_chasis_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engine_chasis_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engine_chasis_boxActionPerformed

    private void subcategory_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subcategory_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subcategory_boxActionPerformed

    private void category_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_boxActionPerformed
 try
        {        
                  Connection myconnection;
        
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                 myconnection=DriverManager.getConnection(path+place, uname, pass);
                 try{
                                    String b="select subcatname from subcategorytable where catname=?";
                                    PreparedStatement mystatement=myconnection.prepareStatement(b);
                                    mystatement.setString(1, category_box.getSelectedItem().toString());
                                    ResultSet myresult = mystatement.executeQuery();
                                    if(myresult.next())
                                        {
                                                subcategory_box.removeAllItems();
                                                subcategory_box.addItem("choose subtype now");
                                            do
                                                 {subcategory_box.addItem(myresult.getString("subcatname"));
                                                 }
                                            while(myresult.next());
                                        
                                        }
                                   else
                                    { JOptionPane.showMessageDialog(rootPane, "No subcategories exist");
                                    }
                                    
                                    
                                    
         
                   }
 
 
               catch(Exception e)
                  {
              JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
                  }
                finally
                {
                 myconnection.close();
                }
 
 
         }
     catch(Exception e)
            {
             JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }

                        
    }//GEN-LAST:event_category_boxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> category_box;
    private org.apache.batik.css.engine.value.svg.ColorProfileManager colorProfileManager1;
    private javax.swing.JFormattedTextField contact_box;
    private java.awt.TextField custome_id_namebox;
    private java.awt.TextArea customer_addbox;
    private javax.swing.JFormattedTextField date1box;
    private javax.swing.JFormattedTextField date2box;
    private javax.swing.JFormattedTextField engine_chasis_box;
    private javax.swing.JFormattedTextField insured_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JFormattedTextField periods_box;
    private javax.swing.JComboBox<String> subcategory_box;
    private javax.swing.JTextField vehicle_box;
    // End of variables declaration//GEN-END:variables
}
