/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;
import java.sql.*;

import javax.swing.JOptionPane;
/**
 *
 * @author PC
 */
public class project5 extends javax.swing.JInternalFrame {

    /**
     * Creates new form project2
     */
    public project5() {
        initComponents();
        try
        {        
                  Connection myconnection;
        
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                 myconnection=DriverManager.getConnection(path+place, uname, pass);
                 try{
                                    String b="select * from categorytable";
                                    PreparedStatement mystatement=myconnection.prepareStatement(b);
                                    ResultSet myresult = mystatement.executeQuery();
                                    if(myresult.next())
                                        {do
                                            {    choosecategorybox.addItem(myresult.getString("catname"));
                                            }
                                        while(myresult.next());
                                        }
                                   else
                                    { JOptionPane.showMessageDialog(rootPane, "No categories exist");
                                    }
                                    
                                    
                                    
         
                   }
 
 
               catch(Exception e)
                  {
              JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
                  }
                finally
                {
                 myconnection.close();
                }
 
 
         }
     catch(Exception e)
            {
             JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }

             }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        label1 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        label6 = new java.awt.Label();
        label2 = new java.awt.Label();
        choosecategorybox = new javax.swing.JComboBox<>();
        subcategorybox = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        setClosable(true);
        setForeground(java.awt.Color.green);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ADD SUBTYPE OF INSURANCE");
        getContentPane().setLayout(null);

        label1.setBackground(new java.awt.Color(204, 204, 255));
        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("INSURANCE TYPE NAME");
        getContentPane().add(label1);
        label1.setBounds(130, 160, 162, 39);

        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 310, 137, 31);

        label6.setBackground(new java.awt.Color(255, 153, 204));
        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setName(""); // NOI18N
        label6.setText("      ADD SUBTYPE OF INSURANCE");
        getContentPane().add(label6);
        label6.setBounds(200, 30, 350, 53);

        label2.setBackground(new java.awt.Color(204, 204, 255));
        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("INSURANCE SUBTYPE NAME");
        getContentPane().add(label2);
        label2.setBounds(130, 240, 162, 39);

        choosecategorybox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        choosecategorybox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE TYPE" }));
        choosecategorybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosecategoryboxActionPerformed(evt);
            }
        });
        getContentPane().add(choosecategorybox);
        choosecategorybox.setBounds(310, 160, 271, 39);

        subcategorybox.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(subcategorybox);
        subcategorybox.setBounds(310, 240, 271, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\Colorful-and-plain-theme-abstract-wallpapers.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 710, 430);

        setBounds(0, 0, 708, 454);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try
           {
                 Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                  myconnection=DriverManager.getConnection(path+place, uname, pass);
 
             try
             {
                    String a="insert into subcategorytable values(?,?)";
                    PreparedStatement mystatement=myconnection.prepareStatement(a);
                    mystatement.setString(1, choosecategorybox.getSelectedItem().toString());
                    mystatement.setString(2, subcategorybox.getText());
                              
                    
                  
 if(mystatement.executeUpdate()>0)
 {
   JOptionPane.showMessageDialog(rootPane, "Saved Successfully");
   //choosecategorybox.setSelectedIndex(0);
   subcategorybox.setText("");
  
           
                                           
 }
 
 }
 catch(Exception e)
 {
   JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 
 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }

             

    }//GEN-LAST:event_jButton1ActionPerformed

    private void choosecategoryboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosecategoryboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choosecategoryboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> choosecategorybox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label6;
    private java.awt.TextField subcategorybox;
    // End of variables declaration//GEN-END:variables
}
