/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

import java.sql.*;

import javax.swing.JOptionPane;
/**
 *
 * @author PC
 */
public class project4 extends javax.swing.JInternalFrame {

    /**
     * Creates new form project2
     */
    public project4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        label6 = new java.awt.Label();
        categorybox = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\coolest-desktop-backgrounds-plain-plain-desktop-wallpapers-wallpapers-desktop-backgrounds-plain.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        setBorder(javax.swing.BorderFactory.createCompoundBorder());
        setClosable(true);
        setForeground(java.awt.Color.red);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ADD TYPE OF INSURANCE");
        setFont(new java.awt.Font("Agency FB", 1, 10)); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("TYPE OF INSURANCE");
        getContentPane().add(label1);
        label1.setBounds(180, 170, 120, 40);

        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 260, 137, 31);

        label6.setBackground(new java.awt.Color(255, 204, 204));
        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setName(""); // NOI18N
        label6.setText("        ADD TYPE OF INSURANCE");
        getContentPane().add(label6);
        label6.setBounds(220, 40, 350, 53);

        categorybox.setBackground(new java.awt.Color(204, 255, 255));
        categorybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryboxActionPerformed(evt);
            }
        });
        getContentPane().add(categorybox);
        categorybox.setBounds(330, 170, 248, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\Colorful-and-plain-theme-abstract-wallpapers.jpg")); // NOI18N
        jLabel6.setName("ADD TYPE OF INSURANCE"); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 740, 420);

        setBounds(0, 0, 737, 441);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             try
           {
                 Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                  myconnection=DriverManager.getConnection(path+place, uname, pass);
 
             try
             {
                    String a="insert into categorytable values(?)";
                    PreparedStatement mystatement=myconnection.prepareStatement(a);
                    mystatement.setString(1,categorybox.getText());
                              
                    
                  
 if(mystatement.executeUpdate()>0)
 {
   JOptionPane.showMessageDialog(rootPane, "Saved Successfully");
   categorybox.setText("");
  
           
                                           
 }
 
 }
 catch(Exception e)
 {
   JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 
 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void categoryboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private java.awt.TextField categorybox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private java.awt.Label label1;
    private java.awt.Label label6;
    // End of variables declaration//GEN-END:variables
}
