/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class update_companydetail extends javax.swing.JInternalFrame {

    /**
     * Creates new form company_detail
     */
    public update_companydetail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cid_box = new javax.swing.JTextField();
        c_namebox = new javax.swing.JTextField();
        c_codebox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        add_box = new javax.swing.JTextArea();
        mail_box = new javax.swing.JTextField();
        tel_box = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("EDIT COMPANY DETAILS");
        setAutoscrolls(true);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 255, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setText("      EDIT COMPANY DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 70, 275, 48);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("COMPANY ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 150, 94, 16);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(585, 246, 0, 0);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 51));
        jLabel9.setText("COMPANY NAME");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 190, 94, 16);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("TELEPHONE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 280, 68, 16);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("E-MAIL");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(160, 440, 39, 16);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("OFFICE ADDRESS");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(160, 330, 97, 16);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("COMPANY CODE");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(160, 240, 93, 16);

        cid_box.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(cid_box);
        cid_box.setBounds(340, 150, 160, 30);

        c_namebox.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(c_namebox);
        c_namebox.setBounds(340, 190, 160, 30);

        c_codebox.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(c_codebox);
        c_codebox.setBounds(340, 230, 160, 30);

        add_box.setBackground(new java.awt.Color(255, 204, 204));
        add_box.setColumns(20);
        add_box.setRows(5);
        jScrollPane1.setViewportView(add_box);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 320, 160, 81);

        mail_box.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(mail_box);
        mail_box.setBounds(340, 430, 160, 30);

        tel_box.setBackground(new java.awt.Color(255, 204, 204));
        tel_box.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##########"))));
        getContentPane().add(tel_box);
        tel_box.setBounds(340, 270, 160, 30);

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 490, 80, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COMPANY_ID", "COMPANY_NAME", "COMPANY_CODE", "TELEPHONE", "ADDRESS", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(650, 90, 630, 402);

        jButton2.setText("SEARCH");
        jButton2.setActionCommand("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(530, 150, 80, 23);

        jButton3.setText("SEARCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(530, 190, 80, 23);

        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(450, 490, 73, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\5220071-plain-picture.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-30, -10, 1600, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                try
           {
                 Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                  myconnection=DriverManager.getConnection(path+place, uname, pass);
 
             try
             {
                    String a="update company_table set company_name=?,"+"company_code=?,telphone=?, address=?,email=?"+"where company_id=?";
                    PreparedStatement mystatement=myconnection.prepareStatement(a);
                    mystatement.setString(6,cid_box .getText());
                    mystatement.setString(1, c_namebox.getText());
                    mystatement.setString(2, c_codebox.getText());
                    mystatement.setString(3, tel_box.getText());
                    mystatement.setString(4, add_box.getText());
                   
                    mystatement.setString(5, mail_box.getText());
                    
 if(mystatement.executeUpdate()>0)
 {
   JOptionPane.showMessageDialog(rootPane, "update Successfully");
   cid_box.setText("");
   c_namebox.setText("");
   c_codebox.setText("");
   tel_box.setText("");
   add_box.setText("");
  
   mail_box.setText("");
   
                                           
 }
 
 }
 catch(Exception e)
 {
   JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 
 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 try
 {    Connection myconnection;
        
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                 myconnection=DriverManager.getConnection(path+place, uname, pass);
 
 
                      try
                        {
                          String myquery="select * from company_table where company_id like ?";
                          PreparedStatement mystatement = myconnection.prepareStatement(myquery);
                          mystatement.setString(1, "%" + cid_box.getText() + "%");
                          ResultSet myresult=mystatement.executeQuery();
 
                         if(myresult.next())
                            {
                              DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
                              String COMPANY_ID,COMPANY_NAME,COMPANY_CODE,TELEPHONE,ADDRESS,EMAIL;
                              mymodel.setRowCount(0);
                              do
                              { 
                                           COMPANY_ID=myresult.getString("company_id");
                                           COMPANY_NAME=myresult.getString("company_name");
                                           COMPANY_CODE=myresult.getString("company_code");
                                           TELEPHONE=myresult.getString("telphone");
                                           ADDRESS=myresult.getString("address");
                                           EMAIL=myresult.getString("email");
                                           
                                          
                                        
                                mymodel.addRow(new Object[]{COMPANY_ID,COMPANY_NAME,COMPANY_CODE,TELEPHONE,ADDRESS,EMAIL});
                               }
                               while(myresult.next());
 
                               }
                        else
                        {
                          JOptionPane.showMessageDialog(rootPane,"No Info available");
                         }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Query due to " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection due to " + e.getMessage());
 }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try
 {    Connection myconnection;
        
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                 myconnection=DriverManager.getConnection(path+place, uname, pass);
 
 
                      try
                        {
                          String myquery="select * from company_table where company_name like ?";
                          PreparedStatement mystatement = myconnection.prepareStatement(myquery);
                          mystatement.setString(1, "%" + c_namebox.getText() + "%");
                          ResultSet myresult=mystatement.executeQuery();
 
                         if(myresult.next())
                            {
                              DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
                              String COMPANY_ID,COMPANY_NAME,COMPANY_CODE,TELEPHONE,ADDRESS,EMAIL;
                              mymodel.setRowCount(0);
                              do
                              { 
                                           COMPANY_ID=myresult.getString("company_id");
                                           COMPANY_NAME=myresult.getString("company_name");
                                           COMPANY_CODE=myresult.getString("company_code");
                                           TELEPHONE=myresult.getString("telphone");
                                           ADDRESS=myresult.getString("address");
                                           EMAIL=myresult.getString("email");
                                           
                                          
                                        
                                mymodel.addRow(new Object[]{COMPANY_ID,COMPANY_NAME,COMPANY_CODE,TELEPHONE,ADDRESS,EMAIL});
                               }
                               while(myresult.next());
 
                               }
                        else
                        {
                          JOptionPane.showMessageDialog(rootPane,"No Info available");
                         }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Query due to " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection due to " + e.getMessage());
 }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                int result=JOptionPane.showConfirmDialog(rootPane, "Do you really want to delete?", 
                  "Are you sure?", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
 
           if(result==JOptionPane.YES_OPTION)
  {
          try
       {
                 Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                 myconnection=DriverManager.getConnection(path+place, uname, pass);
 
               try
                {
                   String a="delete from company_table where company_id=?";
                   PreparedStatement mystatement=myconnection.prepareStatement(a); 
                   mystatement.setString(1, cid_box.getText());
 
                  if(mystatement.executeUpdate()>0)
                     
 {
 JOptionPane.showMessageDialog(rootPane, "Deleted Successfully");
     cid_box.setText("");
   c_namebox.setText("");
   c_codebox.setText("");
   tel_box.setText("");
   add_box.setText("");
  
   mail_box.setText("");
 }
 else
 {
 JOptionPane.showMessageDialog(rootPane, "Cannot delete");
 }
 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 
 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }
 }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
int row = jTable1.getSelectedRow();
 int column = 0;
 String COMPANY_ID=jTable1.getValueAt(row, column).toString();
 try
 { Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                 myconnection=DriverManager.getConnection(path+place, uname, pass);
 
 try
 {
 String myquery="select * from company_table where company_id=?";
 PreparedStatement mystatement = myconnection.prepareStatement(myquery);
 mystatement.setString(1, COMPANY_ID);
 ResultSet myresult=mystatement.executeQuery();
 
 if(myresult.next())
 {
cid_box.setText(COMPANY_ID);

                                                  c_namebox.setText(myresult.getString("company_name"));
                                           c_codebox.setText(myresult.getString("company_code"));
                                        
                                           tel_box.setText(myresult.getString("telphone"));
                                           add_box.setText(myresult.getString("address"));
                                           mail_box.setText(myresult.getString("email"));
 }
 else
 {
 JOptionPane.showMessageDialog(rootPane,"no customer ID");
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Query due to " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection due to " + e.getMessage());
 }        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea add_box;
    private javax.swing.JTextField c_codebox;
    private javax.swing.JTextField c_namebox;
    private javax.swing.JTextField cid_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mail_box;
    private javax.swing.JFormattedTextField tel_box;
    // End of variables declaration//GEN-END:variables
}
