/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PC
 */
public class update_product extends javax.swing.JInternalFrame {

    /**
     * Creates new form project2
     */
    public update_product() {
        initComponents();
         try
        {        
                  Connection myconnection;
        
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                 myconnection=DriverManager.getConnection(path+place, uname, pass);
                 try{
                                    String b="select * from categorytable";
                                    PreparedStatement mystatement=myconnection.prepareStatement(b);
                                    ResultSet myresult = mystatement.executeQuery();
                                    if(myresult.next())
                                        {do
                                            {    category_box.addItem(myresult.getString("catname"));
                                            }
                                        while(myresult.next());
                                        }
                                   else
                                    { JOptionPane.showMessageDialog(rootPane, "No categories exist");
                                    }
                                    
                                    
                                    
         
                   }
 
 
               catch(Exception e)
                  {
              JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
                  }
                finally
                {
                 myconnection.close();
                }
 
 
         }
     catch(Exception e)
            {
             JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        colorProfileManager1 = new org.apache.batik.css.engine.value.svg.ColorProfileManager();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        customer_id_namebox = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        periods_box = new javax.swing.JFormattedTextField();
        insured_box = new javax.swing.JFormattedTextField();
        engine_chasis_box = new javax.swing.JFormattedTextField();
        label6 = new java.awt.Label();
        jButton2 = new javax.swing.JButton();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        category_box = new javax.swing.JComboBox<>();
        subcategory_box = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        date1box = new javax.swing.JFormattedTextField();
        date2box = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        customer_addbox = new java.awt.TextArea();
        vehicle_box = new javax.swing.JTextField();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        contact_box = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        label11 = new java.awt.Label();

        setBackground(new java.awt.Color(255, 204, 204));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 153, 0)));
        setClosable(true);
        setForeground(new java.awt.Color(204, 255, 51));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("EDIT CUSTOMERS DETAIL");
        setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/editPencil.png"))); // NOI18N
        getContentPane().setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("ENGINE NO./CHASIS NO.");
        getContentPane().add(label1);
        label1.setBounds(60, 110, 149, 23);

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("CUSTOMER ID/CUSTOMER NAME");
        getContentPane().add(label2);
        label2.setBounds(60, 70, 187, 20);

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("CONTACT NO.");
        getContentPane().add(label3);
        label3.setBounds(60, 200, 96, 20);

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("DATE OF INSURANCE");
        getContentPane().add(label4);
        label4.setBounds(60, 270, 198, 30);

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("INSURED VALUE");
        getContentPane().add(label5);
        label5.setBounds(60, 370, 96, 20);

        customer_id_namebox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        customer_id_namebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_id_nameboxActionPerformed(evt);
            }
        });
        getContentPane().add(customer_id_namebox);
        customer_id_namebox.setBounds(280, 70, 156, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 530, 109, 23);

        periods_box.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        periods_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periods_boxActionPerformed(evt);
            }
        });
        getContentPane().add(periods_box);
        periods_box.setBounds(280, 230, 156, 30);

        insured_box.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        insured_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insured_boxActionPerformed(evt);
            }
        });
        getContentPane().add(insured_box);
        insured_box.setBounds(280, 370, 156, 30);

        engine_chasis_box.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        engine_chasis_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engine_chasis_boxActionPerformed(evt);
            }
        });
        getContentPane().add(engine_chasis_box);
        engine_chasis_box.setBounds(280, 110, 156, 30);

        label6.setBackground(new java.awt.Color(0, 204, 204));
        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setForeground(new java.awt.Color(0, 0, 255));
        label6.setName(""); // NOI18N
        label6.setText("         EDIT CUSTOMERS'S DETAIL");
        getContentPane().add(label6);
        label6.setBounds(529, 0, 310, 53);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.png"))); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(464, 0, 55, 53);

        label7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label7.setText("INSURANCE SUBTYPE");
        getContentPane().add(label7);
        label7.setBounds(60, 340, 126, 20);

        label8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label8.setText("INSURANCE TYPE");
        getContentPane().add(label8);
        label8.setBounds(60, 310, 110, 20);

        category_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE TYPE" }));
        category_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_boxActionPerformed(evt);
            }
        });
        getContentPane().add(category_box);
        category_box.setBounds(280, 310, 156, 20);

        subcategory_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE TYPE FIRST" }));
        subcategory_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subcategory_boxActionPerformed(evt);
            }
        });
        getContentPane().add(subcategory_box);
        subcategory_box.setBounds(280, 340, 160, 20);

        jButton3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 530, 109, 23);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 204));
        jButton5.setText("SEARCH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(460, 70, 90, 19);

        jLabel2.setText("  TO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 280, 30, 14);

        date1box.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        getContentPane().add(date1box);
        date1box.setBounds(280, 270, 80, 30);

        date2box.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        getContentPane().add(date2box);
        date2box.setBounds(410, 270, 80, 30);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setForeground(new java.awt.Color(0, 102, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUSTOMERDETAIL", "ENGINECHASISNO", "INSUREDVALUE", "PERIOD", "CONTACT", "FROMDATE", "UPTO", "VEHICALDETAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(510, 110, 810, 403);
        getContentPane().add(customer_addbox);
        customer_addbox.setBounds(280, 420, 177, 80);
        getContentPane().add(vehicle_box);
        vehicle_box.setBounds(280, 150, 156, 30);

        label9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label9.setText("VEHICLE NO./VEHICLE NAME/MFD.YEAR");
        getContentPane().add(label9);
        label9.setBounds(60, 160, 195, 20);

        label10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label10.setText("ADDRESS");
        getContentPane().add(label10);
        label10.setBounds(60, 420, 195, 20);

        contact_box.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##########"))));
        getContentPane().add(contact_box);
        contact_box.setBounds(280, 190, 160, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\5220071-plain-picture.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 300, 1490, 910);

        label11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label11.setText("PERIODS OF INSURANCE (in years)");
        getContentPane().add(label11);
        label11.setBounds(60, 240, 198, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void periods_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periods_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periods_boxActionPerformed

    private void customer_id_nameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_id_nameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_id_nameboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             try
           {
                 Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                  myconnection=DriverManager.getConnection(path+place, uname, pass);
 
             try
             {
                    String a="update producttable set engine_chasis=?,"+"contact_no=?,periods=?, insuredvalue=?,catname=?, subcatname=?,date1=?,date2=?,address=?,vehicle_no_name=?"+"where customer_id_nam=?";
                    PreparedStatement mystatement=myconnection.prepareStatement(a);
                    mystatement.setString(11,customer_id_namebox .getText());
                    mystatement.setString(1, engine_chasis_box.getText());
                    mystatement.setString(2, contact_box.getText());
                    mystatement.setString(3, periods_box.getText());
                    mystatement.setString(4, insured_box.getText());
                    mystatement.setString(5, category_box.getSelectedItem().toString());
                    mystatement.setString(6, subcategory_box.getSelectedItem().toString());
                    mystatement.setString(7, date1box.getText());
                    mystatement.setString(8, date2box.getText());
                    mystatement.setString(9, customer_addbox.getText());
                    mystatement.setString(10, vehicle_box.getText());
                    
 if(mystatement.executeUpdate()>0)
 {
   JOptionPane.showMessageDialog(rootPane, "update Successfully");
   engine_chasis_box.setText("");
   customer_id_namebox.setText("");
   contact_box.setText("");
   periods_box.setText("");
   insured_box.setText("");
  
   category_box.setSelectedIndex(0);
   subcategory_box.setSelectedIndex(0);
    date1box.setText("");
   date2box.setText("");
   customer_addbox.setText("");
   vehicle_box.setText("");
           
                                           
 }
 
 }
 catch(Exception e)
 {
   JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 
 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void engine_chasis_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engine_chasis_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engine_chasis_boxActionPerformed

    private void subcategory_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subcategory_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subcategory_boxActionPerformed

    private void category_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_boxActionPerformed
 try
        {        
                  Connection myconnection;
        
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                 myconnection=DriverManager.getConnection(path+place, uname, pass);
                 try{
                                    String b="select subcatname from subcategorytable where catname=?";
                                    PreparedStatement mystatement=myconnection.prepareStatement(b);
                                    mystatement.setString(1, category_box.getSelectedItem().toString());
                                    ResultSet myresult = mystatement.executeQuery();
                                    if(myresult.next())
                                        {
                                                subcategory_box.removeAllItems();
                                                subcategory_box.addItem("choose subtype now");
                                            do
                                                 {subcategory_box.addItem(myresult.getString("subcatname"));
                                                 }
                                            while(myresult.next());
                                        
                                        }
                                   else
                                    { JOptionPane.showMessageDialog(rootPane, "No subcategories exist");
                                    }
                                    
                                    
                                    
         
                   }
 
 
               catch(Exception e)
                  {
              JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
                  }
                finally
                {
                 myconnection.close();
                }
 
 
         }
     catch(Exception e)
            {
             JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }

                        
    }//GEN-LAST:event_category_boxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                  int result=JOptionPane.showConfirmDialog(rootPane, "Do you really want to delete?", 
                  "Are you sure?", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
 
           if(result==JOptionPane.YES_OPTION)
  {
          try
       {
                 Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                 myconnection=DriverManager.getConnection(path+place, uname, pass);
 
               try
                {
                   String a="delete from producttable where customer_id_nam=?";
                   PreparedStatement mystatement=myconnection.prepareStatement(a); 
                   mystatement.setString(1, customer_id_namebox.getText());
 
                  if(mystatement.executeUpdate()>0)
                     
 {
 JOptionPane.showMessageDialog(rootPane, "Deleted Successfully");
  engine_chasis_box.setText("");
   customer_id_namebox.setText("");
   contact_box.setText("");
   periods_box.setText("");
   insured_box.setText("");
   date1box.setText("");
   date2box.setText("");
    customer_addbox.setText("");
   vehicle_box.setText("");
 }
 else
 {
 JOptionPane.showMessageDialog(rootPane, "Cannot delete");
 }
 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 
 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }
 }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 try
 {    Connection myconnection;
        
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                 myconnection=DriverManager.getConnection(path+place, uname, pass);
 
 
                      try
                        {
                          String myquery="select * from producttable where customer_id_nam like ?";
                          PreparedStatement mystatement = myconnection.prepareStatement(myquery);
                          mystatement.setString(1, "%" + customer_id_namebox.getText() + "%");
                          ResultSet myresult=mystatement.executeQuery();
 
                         if(myresult.next())
                            {
                              DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
                              String CUSTOMERDETAIL,ENGINECHASISNO,INSUREDVALUE,PERIOD,CONTACT,FROMDATE,UPTO,VEHICLEDETAIL;
                              mymodel.setRowCount(0);
                              do
                              { 
                                           CUSTOMERDETAIL=myresult.getString("customer_id_nam");
                                           ENGINECHASISNO=myresult.getString("engine_chasis");
                                           INSUREDVALUE=myresult.getString("insuredvalue");
                                           PERIOD=myresult.getString("periods");
                                           CONTACT=myresult.getString("contact_no");
                                           FROMDATE=myresult.getString("date1");
                                           UPTO=myresult.getString("date2");
                                          
                                           VEHICLEDETAIL=myresult.getString("vehicle_no_name");
                                mymodel.addRow(new Object[]{CUSTOMERDETAIL,ENGINECHASISNO,INSUREDVALUE,PERIOD,CONTACT,FROMDATE,UPTO,VEHICLEDETAIL});
                               }
                               while(myresult.next());
 
                               }
                        else
                        {
                          JOptionPane.showMessageDialog(rootPane,"No Info available");
                         }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Query due to " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection due to " + e.getMessage());
 }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void insured_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insured_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insured_boxActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
int row = jTable1.getSelectedRow();
 int column = 0;
 String CUSTOMERDETAIL=jTable1.getValueAt(row, column).toString();
 try
 { Connection myconnection;
                 String path="jdbc:mysql://localhost/";
                 String place="category";
                 String uname="root" ;
                
                 String pass="";
                 myconnection=DriverManager.getConnection(path+place, uname, pass);
 
 try
 {
 String myquery="select * from producttable where customer_id_nam=?";
 PreparedStatement mystatement = myconnection.prepareStatement(myquery);
 mystatement.setString(1, CUSTOMERDETAIL);
 ResultSet myresult=mystatement.executeQuery();
 
 if(myresult.next())
 {
customer_id_namebox .setText(CUSTOMERDETAIL);
engine_chasis_box .setText(myresult.getString("engine_chasis"));
                                                contact_box.setText(myresult.getString("contact_no"));
                                                 periods_box.setText(myresult.getString("periods"));
                                                 insured_box .setText(myresult.getString("insuredvalue"));
                                                   category_box.setSelectedItem(myresult.getString("catname"));
                                                    subcategory_box.setSelectedItem(myresult.getString("subcatname"));
                                                     date1box .setText(myresult.getString("date1"));
                                                      date2box .setText(myresult.getString("date2"));
                                                        customer_addbox.setText(myresult.getString("address"));
                                                        vehicle_box.setText(myresult.getString("vehicle_no_name"));
 }
 else
 {
 JOptionPane.showMessageDialog(rootPane,"no customer ID");
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Query due to " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection due to " + e.getMessage());
 }        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> category_box;
    private org.apache.batik.css.engine.value.svg.ColorProfileManager colorProfileManager1;
    private javax.swing.JFormattedTextField contact_box;
    private java.awt.TextArea customer_addbox;
    private java.awt.TextField customer_id_namebox;
    private javax.swing.JFormattedTextField date1box;
    private javax.swing.JFormattedTextField date2box;
    private javax.swing.JFormattedTextField engine_chasis_box;
    private javax.swing.JFormattedTextField insured_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JFormattedTextField periods_box;
    private javax.swing.JComboBox<String> subcategory_box;
    private javax.swing.JTextField vehicle_box;
    // End of variables declaration//GEN-END:variables
}
